### ISSUE TITLE
0.2.0 AppStore Compatibility

### ISSUE THREAD

**Issue by JacksonUtsch** [pointfreeco/xctest-dynamic-overlay#10]
0.2.0 enacted "Changed: XCTFail is no longer restricted to DEBUG builds."

It seems like Apple does not like this in production. When submitting for review I got the response that included: "Non-public API usage - The app references non-public symbols in ---: __swift_FORCE_LOAD_$_XCTestSwiftSupport."

In order to compile my project I also need to set "Enable Testing Search Paths" to Yes or I get the undefined symbol __swift_FORCE_LOAD_$_XCTestSwiftSupport

Should this package only target testTargets in SPM?

**Comment by stephencelis** [comment]
Ah interesting. We can revert that change and explore other ways of restoring test functionality outside debug builds in the future.

**Comment by JacksonUtsch** [comment]
Thanks!

**Comment by stephencelis** [comment]
Just released [0.2.1](https://github.com/pointfreeco/xctest-dynamic-overlay/releases/tag/0.2.1)! Please let us know if you have any more issues.

**Comment by stephencelis** [comment]
@JacksonUtsch I know it's been some time but do you remember how this App Store submission failure occurred? Was it immediately during the submission process? Or did it come later on in the review period.

We're revisiting this because we'd love to make XCTestDynamicOverlay work in release builds, so it'd be helpful to know what Apple is on the watch for and how.

**Comment by JacksonUtsch** [comment]
@stephencelis This occurred after a successful submission, I'm pretty certain it was automated. The error code given was `ITMS-90338`. There are online positing of issues with people utilizing private APIs having the same issue.

I'd be interested to know the use case of having this work in release builds rather than no-op.

**Comment by stephencelis** [comment]
@JacksonUtsch Being able to run tests on release is valuable, and possible using vanilla XCTest tools, but because we currently compile everything out of RELEASE builds, no code using XCTestDynamicOverlay can be run in release at all.

**Comment by mbrandonw** [comment]
Hi @JacksonUtsch, sorry to resurrect such an old issue for the second time, but we are once again looking into the possibility of removing `#if DEBUG` from this library.

Upon re-reading your original issue it seems that your problem may have actually been unrelated to the 0.2.0 release that removed the `#if DEBUG`. It seems like you explicitly turned on the "Enable Testing Search Paths" setting in your Xcode project, which force links XCTest with the application target. That seems to be the actual reason your application was rejected, not due to the symbols that ship in this library.

Can you explain a bit more why you turned on "Enable Testing Search Paths"?

**Comment by JacksonUtsch** [comment]
"Enable Testing Search Paths" was enabled to get the compiler to build when I got the error from adopting 0.2.0 `Undefined symbol _swift_FORCE_LOAD$_XCTestSwiftSupport`. I was able to reproduce this error after some digging. If you import [this branch](https://github.com/JacksonUtsch/Architecture/tree/xctest-10) into a project and make sure xctest is at 0.2.0 you should get the same error. 
<img width="432" alt="Screenshot 2023-04-10 at 11 40 02 AM" src="https://user-images.githubusercontent.com/5590250/230970126-be1f6261-eb65-495f-b008-f627625cac98.png">

**Comment by mbrandonw** [comment]
Hi @JacksonUtsch, thanks for the repro, but I don't think this is related to xctest-dynamic-overlay at all. I think this is related to the fact that you are importing XCTest directly [here](https://github.com/JacksonUtsch/Architecture/blob/462e008b7cb0270a0de98148661a3880940f72f6/Sources/Architecture/Diff.swift#L9). Can you try removing that and see if it fixes your issue?

The `if #DEBUG`s should have no bearing on your library at all since it is building for debug anyway.

**Comment by JacksonUtsch** [comment]
@mbrandonw Hmm, I reluctantly agree 🙈. I removed the import earlier and still had the issue but this time I clean and rebuild and the error goes away!

I now wonder what the sequence of events that happened originally to make it seem like it was a issue with 0.2.0. All the better to move forward with release support then 🙃
